version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://oss:svXsnZVVUUybzNwgdVGWJpgYFzchBw@postgres:5432/oss
      - REDIS_URL=redis://redis:6379
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
  frontend:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "oss"
      POSTGRES_USER: "oss"
      POSTGRES_PASSWORD: "svXsnZVVUUybzNwgdVGWJpgYFzchBw"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server
    ports:
      - "6384:6379"
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
