// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"oss-backend/internal/config"
	"oss-backend/internal/service/httpserver"
)

// Injectors from wire.go:

func Up() (*Dependencies, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	httpServer := httpserver.New(configConfig)
	dependencies := NewDependencies(configConfig, httpServer)
	return dependencies, nil
}

// wire.go:

func getPostgresConfig(cfg config.Config) config.Postgres {
	return cfg.Postgres
}
